SQL Schema
Pandas Schema
Table: Customers

+-------------+---------+
| Column Name | Type    |
+-------------+---------+
| id          | int     |
| name        | varchar |
+-------------+---------+
id is the primary key (column with unique values) for this table.
Each row of this table indicates the ID and name of a customer.
 

Table: Orders

+-------------+------+
| Column Name | Type |
+-------------+------+
| id          | int  |
| customerId  | int  |
+-------------+------+
id is the primary key (column with unique values) for this table.
customerId is a foreign key (reference columns) of the ID from the Customers table.
Each row of this table indicates the ID of an order and the ID of the customer who ordered it.
 

Write a solution to find all customers who never order anything.

Return the result table in any order.

The result format is in the following example.

 

Example 1:

Input: 
Customers table:
+----+-------+
| id | name  |
+----+-------+
| 1  | Joe   |
| 2  | Henry |
| 3  | Sam   |
| 4  | Max   |
+----+-------+
Orders table:
+----+------------+
| id | customerId |
+----+------------+
| 1  | 3          |
| 2  | 1          |
+----+------------+
Output: 
+-----------+
| Customers |
+-----------+
| Henry     |
| Max       |
+-----------+

In [1]:
import pandas as pd

# Customers table
customers = pd.DataFrame({
    "id": [1, 2, 3, 4],
    "name": ["Joe", "Henry", "Sam", "Max"]
})

# Orders table
orders = pd.DataFrame({
    "id": [1, 2],
    "customerId": [3, 1]
})

In [2]:
customers

   id   name
0   1    Joe
1   2  Henry
2   3    Sam
3   4    Max

In [3]:
orders

   id  customerId
0   1           3
1   2           1

In [4]:
def find_customers(customers: pd.DataFrame, orders: pd.DataFrame) -> pd.DataFrame:
    result = customers[~customers["id"].isin(orders["customerId"])]
    return result[["name"]].rename(columns={"name": "Customers"})

In [5]:
find_customers(customers, orders)

  Customers
1     Henry
3       Max

## OR

In [8]:
import pandas as pd

def find_customers(customers: pd.DataFrame, orders: pd.DataFrame) -> pd.DataFrame:
    merged = customers.merge(
        orders,
        left_on="id",
        right_on="customerId",
        how="left"
    )
    
    result = merged[merged["customerId"].isna()][["name"]]
    result.columns = ["Customers"]
    
    return result

NameError: name 'result' is not defined