DataFrame customers
+-------------+--------+
| Column Name | Type   |
+-------------+--------+
| customer_id | int    |
| name        | object |
| email       | object |
+-------------+--------+
There are some duplicate rows in the DataFrame based on the email column.

Write a solution to remove these duplicate rows and keep only the first occurrence.

The result format is in the following example.

 

Example 1:
Input:
+-------------+---------+---------------------+
| customer_id | name    | email               |
+-------------+---------+---------------------+
| 1           | Ella    | emily@example.com   |
| 2           | David   | michael@example.com |
| 3           | Zachary | sarah@example.com   |
| 4           | Alice   | john@example.com    |
| 5           | Finn    | john@example.com    |
| 6           | Violet  | alice@example.com   |
+-------------+---------+---------------------+
Output:  
+-------------+---------+---------------------+
| customer_id | name    | email               |
+-------------+---------+---------------------+
| 1           | Ella    | emily@example.com   |
| 2           | David   | michael@example.com |
| 3           | Zachary | sarah@example.com   |
| 4           | Alice   | john@example.com    |
| 6           | Violet  | alice@example.com   |
+-------------+---------+---------------------+
Explanation:
Alic (customer_id = 4) and Finn (customer_id = 5) both use john@example.com, so only the first occurrence of this email is retained.

In [1]:
import pandas as pd

In [2]:
def dropDuplicateEmails(customers: pd.DataFrame) -> pd.DataFrame:
    return customers.drop_duplicates(subset = 'email', keep = 'first')

In [3]:
customers = pd.DataFrame(
    {
        "customer_id" : [1,2,3,4,5,6],
        "name" : ['Ella', 'David', 'Zachary', 'Alice', 'Finn', 'Violet'],
        "email" : ['emily@example.com', 'michael@example.com', 'sarah@example.com', 'john@example.com', 'john@example.com', 'alice@example.com']
    }
)
customers

   customer_id     name                email
0            1     Ella    emily@example.com
1            2    David  michael@example.com
2            3  Zachary    sarah@example.com
3            4    Alice     john@example.com
4            5     Finn     john@example.com
5            6   Violet    alice@example.com

In [4]:
dropDuplicateEmails(customers)

   customer_id     name                email
0            1     Ella    emily@example.com
1            2    David  michael@example.com
2            3  Zachary    sarah@example.com
3            4    Alice     john@example.com
5            6   Violet    alice@example.com